import { PageHero } from '../components/sections/PageHero';
import { Button } from '../components/ui/Button';
import { Container, SectionHeading } from '../components/ui/Section';
import { Seo } from '../components/ui/Seo';
import { process, principles } from '../data/content';
import { site } from '../data/site';

export default function About(){return <><Seo title="About" description={`About ${site.name}, a ${site.role} based in ${site.location}.`}/><PageHero eyebrow={`About ${site.name}`} title="I build digital products that feel clear, fast, and considered." text={`${site.tagline} I combine frontend craft, product thinking, and careful execution from first layout to final deployment.`}/>
<section className="pb-24 sm:pb-28"><Container><div className="grid gap-10 lg:grid-cols-2"><div className="glass-card grid aspect-[4/3] place-items-center rounded-3xl bg-[radial-gradient(circle_at_35%_35%,rgba(155,135,245,.8)_0,transparent_27%),radial-gradient(circle_at_68%_60%,rgba(69,211,199,.65)_0,transparent_23%),var(--glass)]"><span className="font-display text-[clamp(5rem,12vw,9rem)] font-bold tracking-[-.08em] text-[var(--text)] drop-shadow-[0_0_30px_rgba(155,135,245,.35)]">SA</span></div><div className="flex flex-col justify-center"><span className="eyebrow">My point of view</span><p className="mt-7 font-display text-3xl leading-tight tracking-[-.04em] sm:text-5xl">A strong website should be easy to use, hard to ignore, and fast everywhere.</p><p className="mt-7 leading-7 text-[var(--muted)]">I'm {site.name}, a {site.role} from {site.location}. I work across interface design and development, turning ideas into responsive websites, dashboards, and SaaS experiences that are ready for real users.</p><div className="mt-7 flex flex-wrap gap-2">{site.skills.map(skill=><span className="rounded-full border border-[var(--glass-border)] bg-[var(--glass)] px-4 py-2 text-xs font-semibold backdrop-blur-md" key={skill}>{skill}</span>)}</div></div></div></Container></section>
<section className="color-section py-28"><Container><SectionHeading eyebrow="Principles" title="What I protect while I build."/><div className="mt-14 grid gap-5 md:grid-cols-3">{principles.map(p=><div className="glass-card rounded-3xl p-8" key={p.title}><span className="icon-glass"><p.icon size={20}/></span><h3 className="mt-14 font-display text-2xl">{p.title}</h3><p className="mt-4 leading-7 text-[var(--muted)]">{p.text}</p></div>)}</div></Container></section>
<section className="py-24 sm:py-28"><Container><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><SectionHeading eyebrow="Process" title="Eight clear moves from question to outcome."/><Button to="/contact" variant="primary" className="mt-8">Work with me</Button></div><div className="space-y-3">{process.map(([n,t,d])=><div className="glass-card grid gap-3 rounded-2xl p-5 sm:grid-cols-[50px_140px_1fr] sm:p-6" key={n}><span className="text-xs text-violet">{n}</span><h3 className="font-display text-lg">{t}</h3><p className="text-sm leading-6 text-[var(--muted)]">{d}</p></div>)}</div></div></Container></section></>}
