import { ArrowUpRight, Clock3 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageHero } from '../components/sections/PageHero';
import { Container } from '../components/ui/Section';
import { Seo } from '../components/ui/Seo';
import { articles } from '../data/articles';
import { site } from '../data/site';

export default function Blog(){
  const schema={ '@context':'https://schema.org','@type':'CollectionPage',name:'Developer Blog',url:`${site.url}/blog`,description:'Articles about React, frontend architecture, accessibility, performance, SEO, and product design.',author:{'@id':`${site.url}/#person`},hasPart:articles.map(a=>({'@type':'BlogPosting',headline:a.title,url:`${site.url}/blog/${a.slug}`}))};
  return <><Seo title="Developer Blog" description={`${site.name}'s practical articles about React, frontend architecture, UI/UX, accessibility, SEO, and web performance.`} schema={schema}/><PageHero eyebrow="Developer blog" title="Useful thinking for better web products." text="Practical field notes from building responsive React products at the intersection of design, engineering, accessibility, and performance."/><section className="pb-28"><Container><div className="mb-10 flex flex-wrap gap-2" aria-label="Article topics">{['React','Frontend','UI/UX','Performance','Accessibility','Case Studies','Portfolio','SEO'].map(tag=><span className="rounded-full border border-[var(--border)] px-4 py-2 text-xs text-[var(--muted)]" key={tag}>{tag}</span>)}</div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{articles.map((article,i)=><Link to={`/blog/${article.slug}`} className="glass-card focus-ring group rounded-3xl p-7" key={article.slug}><div className="flex justify-between text-xs text-[var(--muted)]"><span>NO. {String(i+1).padStart(2,'0')}</span><span className="icon-glass size-8 rounded-lg"><ArrowUpRight size={15} aria-hidden="true"/></span></div><div className="mt-16 sm:mt-20"><span className="rounded-full border border-[var(--glass-border)] bg-[var(--glass)] px-3 py-2 text-xs font-bold text-violet">{article.category}</span><h2 className="mt-6 font-display text-2xl font-medium tracking-[-.03em] group-hover:text-violet">{article.title}</h2><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{article.description}</p><span className="mt-6 flex items-center gap-2 text-xs text-[var(--muted)]"><Clock3 size={14}/>{article.readTime} min read</span></div></Link>)}</div></Container></section></>;
}
