import { useParams } from 'react-router-dom';
import { PageHero } from '../components/sections/PageHero';
import { Button } from '../components/ui/Button';
import { Container } from '../components/ui/Section';
import { Seo } from '../components/ui/Seo';
import { projects, technologies } from '../data/content';

export default function ProjectDetail(){const {slug}=useParams(); const p=projects.find(x=>x.slug===slug)??projects[0]; return <><Seo title={p.title} description={`${p.title}: ${p.description}`}/><PageHero eyebrow={`${p.type} · Concept case study`} title={p.title} text={p.description}/><section className="pb-28"><Container><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Engagement','Strategy to launch'],['Timeline','12 weeks'],['Outcome',p.result],['Status','Demo project']].map(([k,v])=><div className="glass-card rounded-2xl p-6 sm:p-8" key={k}><span className="text-xs text-[var(--muted)]">{k}</span><b className="mt-3 block font-display text-xl">{v}</b></div>)}</div><div className="glass-card mt-6 aspect-[16/8] rounded-3xl bg-[radial-gradient(circle_at_35%_45%,rgba(155,135,245,.8)_0,transparent_25%),radial-gradient(circle_at_70%_55%,rgba(100,235,220,.7)_0,transparent_22%),var(--glass)]"/>
<div className="mx-auto mt-20 grid max-w-5xl gap-10 sm:mt-24 md:grid-cols-2"><div><span className="eyebrow">The challenge</span><h2 className="mt-5 font-display text-4xl tracking-[-.04em]">Make complexity feel confidently simple.</h2></div><p className="leading-8 text-[var(--muted)]">The journey had grown around internal systems rather than customer decisions. Important signals competed for attention and frequent tasks felt heavier than they needed to. I reframed the concept around user intent, then made the hierarchy do the hard work.</p></div>
<div className="mx-auto mt-24 grid max-w-5xl gap-12 md:grid-cols-2"><div><span className="eyebrow">The response</span><h2 className="mt-5 font-display text-4xl tracking-[-.04em]">One visual system. A clearer operating model.</h2></div><div><p className="leading-8 text-[var(--muted)]">A modular design language created consistency without flattening the brand. Progressive disclosure reduced noise, new content patterns improved confidence, and a robust component architecture let the product team move faster after launch.</p><div className="mt-7 flex flex-wrap gap-2">{technologies.slice(0,6).map(t=><span className="rounded-full border border-[var(--border)] px-4 py-2 text-xs" key={t}>{t}</span>)}</div></div></div>
<div className="gradient-panel mt-24 rounded-3xl p-8 sm:p-14"><span className="text-xs font-bold uppercase tracking-[.15em]">Demo results</span><p className="mt-5 max-w-4xl font-display text-4xl font-medium tracking-[-.04em] sm:text-6xl">A more useful product and a sharper expression of the business behind it.</p><p className="mt-6 text-sm text-white/75">Metrics shown in this concept study are fictional and included for demonstration.</p></div><div className="mt-20 text-center"><Button to="/contact" variant="primary">Build something meaningful</Button></div></Container></section></>}
