import { Search as SearchIcon } from 'lucide-react';
import { useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { PageHero } from '../components/sections/PageHero';
import { Container } from '../components/ui/Section';
import { Seo } from '../components/ui/Seo';
import { articles } from '../data/articles';
import { projects, services } from '../data/content';

const index=[...projects.map(p=>({title:p.title,text:`${p.description} ${p.stack.join(' ')} ${p.type}`,type:'Case study',url:`/project/${p.slug}`})),...articles.map(a=>({title:a.title,text:`${a.description} ${a.tags.join(' ')} ${a.category}`,type:'Article',url:`/blog/${a.slug}`})),...services.map(s=>({title:s.title,text:s.text,type:'Service',url:'/services'}))];
export default function Search(){const [query,setQuery]=useState('');const input=useRef<HTMLInputElement>(null);const results=useMemo(()=>{const q=query.trim().toLowerCase();return q?index.filter(x=>`${x.title} ${x.text}`.toLowerCase().includes(q)).slice(0,12):index.slice(0,8)},[query]);return <><Seo title="Search" description="Search Sathwik Akkenakunta's projects, case studies, technologies, services, and frontend articles." noIndex/><PageHero eyebrow="Site search" title="Find projects, technologies, and articles." text="Search the portfolio instantly. Results include case studies, services, frontend topics, and technical articles."/><section className="pb-28"><Container><div className="mx-auto max-w-4xl"><label className="relative block"><span className="sr-only">Search the portfolio</span><SearchIcon className="absolute left-5 top-1/2 -translate-y-1/2 text-[var(--muted)]"/><input ref={input} autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Escape'){setQuery('');input.current?.focus()}}} className="focus-ring w-full rounded-2xl border border-[var(--border)] bg-[var(--glass)] py-5 pl-14 pr-5 text-lg outline-none" placeholder="Try React, dashboards, SEO…"/></label><p className="mt-4 text-sm text-[var(--muted)]" aria-live="polite">{results.length} result{results.length===1?'':'s'}{query&&` for “${query}”`}</p><div className="mt-6 grid gap-3">{results.map((result,i)=><Link className="glass-card focus-ring rounded-2xl p-5" to={result.url} key={`${result.url}-${i}`}><span className="text-xs font-bold uppercase tracking-[.12em] text-violet">{result.type}</span><h2 className="mt-2 font-display text-xl"><Highlight text={result.title} query={query}/></h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-[var(--muted)]"><Highlight text={result.text} query={query}/></p></Link>)}</div></div></Container></section></>}
function Highlight({text,query}:{text:string;query:string}){const q=query.trim();if(!q)return text;const index=text.toLowerCase().indexOf(q.toLowerCase());if(index<0)return text;return <>{text.slice(0,index)}<mark className="rounded bg-violet/25 px-0.5 text-[var(--text)]">{text.slice(index,index+q.length)}</mark>{text.slice(index+q.length)}</>}
