import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
const root=resolve(import.meta.dirname,'..');
const siteUrl=(process.env.VITE_SITE_URL||(process.env.VERCEL_PROJECT_PRODUCTION_URL?`https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`:'https://sathwik-studio.vercel.app')).replace(/\/$/,'');
const [template,projectsSource,articlesSource]=await Promise.all([readFile(resolve(root,'dist/index.html'),'utf8'),readFile(resolve(root,'src/data/content.ts'),'utf8'),readFile(resolve(root,'src/data/articles.ts'),'utf8')]);
const pages=[
{path:'/',title:'Sathwik Akkenakunta — Full Stack Web Developer',description:'Sathwik Akkenakunta is a Full Stack Web Developer building premium websites, responsive dashboards, and scalable SaaS applications.'},
{path:'/about',title:'About — Sathwik Akkenakunta',description:'About Sathwik Akkenakunta, a Full Stack Web Developer in Telangana building accessible, responsive web applications.'},
{path:'/projects',title:'Projects — Sathwik Akkenakunta',description:'Explore React websites, dashboards, SaaS applications, and complete frontend case studies built by Sathwik Akkenakunta.'},
{path:'/services',title:'Web Development Services — Sathwik Akkenakunta',description:'React development, responsive websites, dashboards, SaaS applications, UI/UX systems, technical SEO, and performance optimization.'},
{path:'/blog',title:'Developer Blog — Sathwik Akkenakunta',description:'Practical articles about React, JavaScript, frontend architecture, UI/UX, accessibility, SEO, and web performance.'},
{path:'/contact',title:'Contact — Sathwik Akkenakunta',description:'Contact Sathwik Akkenakunta about a modern website, responsive dashboard, or SaaS application.'},
{path:'/faq',title:'FAQs — Sathwik Akkenakunta',description:'Answers about working with Sathwik on websites, React dashboards, and SaaS applications.'},
{path:'/pricing',title:'Engagements — Sathwik Akkenakunta',description:'Flexible project options for websites, landing pages, dashboards, and SaaS applications.'},
{path:'/privacy',title:'Privacy Policy — Sathwik Akkenakunta',description:'Privacy policy for the Sathwik Akkenakunta developer portfolio.'},
{path:'/terms',title:'Terms — Sathwik Akkenakunta',description:'Terms of use for the Sathwik Akkenakunta developer portfolio.'}
];
for(const m of projectsSource.matchAll(/\{ slug: '([^']+)'.*?title: '([^']+)'.*?description: '([^']+)'.*?image: '([^']+)'/g))pages.push({path:`/project/${m[1]}`,title:`${m[2]} Case Study — Sathwik Akkenakunta`,description:`${m[2]} case study: ${m[3]}`,image:m[4],type:'article'});
for(const m of articlesSource.matchAll(/make\(\{slug:'([^']+)',title:'([^']+)',description:'([^']+)'/g))pages.push({path:`/blog/${m[1]}`,title:`${m[2]} — Sathwik Akkenakunta`,description:m[3],type:'article'});
const escape=value=>value.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
for(const page of pages){const url=`${siteUrl}${page.path==='/'?'':page.path}`;const image=`${siteUrl}${page.image||'/og/sathwik-dev.png'}`;const schema={'@context':'https://schema.org','@type':page.type==='article'?'Article':'WebPage',name:page.title,description:page.description,url,image,author:{'@type':'Person',name:'Sathwik Akkenakunta',url:siteUrl}};const tags=`<link rel="canonical" href="${url}"><meta name="robots" content="index, follow, max-image-preview:large"><meta property="og:title" content="${escape(page.title)}"><meta property="og:description" content="${escape(page.description)}"><meta property="og:type" content="${page.type||'website'}"><meta property="og:url" content="${url}"><meta property="og:image" content="${image}"><meta property="og:site_name" content="Sathwik Akkenakunta Portfolio"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(page.title)}"><meta name="twitter:description" content="${escape(page.description)}"><meta name="twitter:image" content="${image}"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>`;const html=template.replace(/<title>.*?<\/title>/,`<title>${escape(page.title)}</title>`).replace(/<meta name="description" content="[^"]*"\s*\/?>/,`<meta name="description" content="${escape(page.description)}">`).replace('</head>',`${tags}</head>`);const output=page.path==='/'?resolve(root,'dist/index.html'):resolve(root,`dist${page.path}.html`);await mkdir(dirname(output),{recursive:true});await writeFile(output,html)}
console.log(`Generated ${pages.length} crawler-ready route shells`);
